# Generated by Django 3.0.2 on 2020-03-30 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='users_post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
