# Generated by Django 3.0.2 on 2020-04-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0002_auto_20200413_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='page_photo/%Y/%m/%d'),
        ),
    ]
