# Generated by Django 3.0.2 on 2020-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0003_profile_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
