# Generated by Django 3.0.2 on 2020-04-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0004_auto_20200414_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, max_length=100, verbose_name='your website link'),
        ),
    ]
