# Generated by Django 3.0.2 on 2020-04-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0005_auto_20200414_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
