# Generated by Django 3.0.2 on 2020-04-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0006_auto_20200414_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='link',
        ),
    ]
