# Generated by Django 3.0.2 on 2020-05-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0009_auto_20200420_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='proffile.Profile'),
        ),
    ]
