# Generated by Django 3.0.2 on 2020-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0012_auto_20200528_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='static/not-found.png', upload_to='page_photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='css/not-found.png', upload_to='profile_photo/%Y/%m/%d'),
        ),
    ]
