# Generated by Django 3.0.2 on 2020-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffile', '0013_auto_20200628_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/css/not-found.png', upload_to='profile_photo/%Y/%m/%d'),
        ),
    ]
